# -*- coding: utf-8 -*-
"""
Config — thin re-export + agentic additions.
Never duplicate v31 constants; import them.
"""
from __future__ import annotations
import os
from pathlib import Path

# Pull everything from v31 so a single source of truth remains.
from scripts.generate_vp_deepseek31_en import (  # noqa: F401
    _env_int, _env_float, _env_bool, _utcnow,
    DEFAULT_MODEL, DEEPSEEK_BASE, DEEPSEEK_APIKEY,
    ENABLE_THINKING, REASONING_EFFORT, TEMPERATURE, MAX_TOKENS,
    API_REQUEST_INTERVAL, API_MAX_RETRIES, API_BACKOFF_BASE,
    MAX_CASE_ATTEMPTS, MAX_STAGE_A_ATTEMPTS, MAX_STAGE_B_ATTEMPTS,
    MAX_L5_REPAIRS, MAX_EVIDENCE_SEARCH_ROUNDS, SLEEP_BETWEEN_VP,
    MAX_REQUESTS_PER_CASE, CASE_DEADLINE_S, MAX_UNKNOWN_TOOL_CALLS,
    MAX_SEARCH_CALLS, MAX_BATCH_TOKENS,
    SEARXNG_BASE_URL_LIST, SEARXNG_LB_STRATEGY, SEARXNG_TIMEOUT_S,
    SEARXNG_SAFESEARCH, ENABLE_WEB_SEARCH, SEARCH_RESULTS_N,
    MAX_QUERY_WORDS, SEARCH_LANGUAGES, ENABLE_SEARCH_CACHE,
    SEARCH_CACHE_PATH, SEARCH_CACHE_TTL_S, SEARCH_EMPTY_CACHE_TTL_S,
    EMPTY_SEARCH_STREAK_ALERT, MIN_SNIPPET_LEN,
    MIN_VERIFIED_SOURCES, ENABLE_EVIDENCE_PACKS, EVIDENCE_PACK_VERSION,
    HOMOGENEITY_THRESHOLD,
    PREFERRED_SOURCE_DOMAINS, PREFERRED_PATH_HINTS,
    BLOCKED_SOURCE_DOMAINS, BLOCKED_HOST_FRAGMENTS,
    ICD11_PATH, OUTPUT_DIR, DB_PATH, PROMPT_VERSION, SCHEMA_VERSION,
    GENERATOR_VERSION,
    SEVERITY_LEVELS, SEVERITY_MATRIX, SEV_INDEX,
    DSM5_NINE_DOMAINS, CORE_KEYS, ADD_KEYS_NON_A9, A9_KEY, ALL_DOMAIN_KEYS,
    SOMATIC_ATTRIBUTION_KEYS,
    MIN_EVIDENCE_CHARS, MIN_TEXT_CHARS, MIN_NARRATIVE_CHARS,
    SYSTEM_PROMPT, SCENARIO_HEADINGS, BLIND_SECTIONS, PATIENT_VOICE_SECTIONS,
    TOOL_NAME_WEB_SEARCH, WEB_SEARCH_TOOL,
    L5_QC_VERSION, L5_AREAS, L5_QC_SYSTEM,
    MASTER_FIELDS, logger,
)

# --- Agentic additions -------------------------------------------------------
PMC_INDEX_PATH = os.environ.get("PMC_INDEX_PATH", str(Path(OUTPUT_DIR) / "pmc_patients" / "pmc_patients.sqlite"))
PMC_TOPK = _env_int("PMC_TOPK", 5)
PMC_CALIBRATE = _env_bool("PMC_CALIBRATE", False)
PMC_MODE = os.environ.get("PMC_MODE", "full")  # full | derm_subset

SIMULATE_DEFAULT = _env_bool("SIMULATE", False)
SIM_TURNS = _env_int("SIM_TURNS", 20)
SIM_BIAS = os.environ.get("SIM_BIAS", "").strip()  # e.g. recency, anchoring, ...

NOTEBOOK_ENABLED = _env_bool("VP_NOTEBOOK", True)
NOTEBOOK_PATH = os.environ.get("VP_NOTEBOOK_PATH", str(Path(OUTPUT_DIR) / "notebooks.sqlite"))

AGENTIC_PROMPT_VERSION = "agentic-host-v1"
AGENTIC_SCHEMA_VERSION = SCHEMA_VERSION + "+agentic"
GENERATOR_VERSION_AGENTIC = "v32-agentic-hybrid-20260922"
